<?php
/***
 * Class Ordersplitter
 * @desc Create invoice splitters and shipment splitters
 */


class Goldie_Partnersales_Model_OrderSplitter extends Mage_Core_Model_Abstract
{
    /***
     * @var Mage_Sales_Model_Order
     */
    protected $order;

    /***
     * Goldie_Partnersales_Model_Ordersplitter constructor.
     *
     * @param Mage_Sales_Model_Order $order
     */
    public function __construct(Mage_Sales_Model_Order $order)
    {
        $this->order = $order;
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    /***
     * Create multiple invoices
     */
    public function splitInvoices()
    {
        $orderItems = $this->order->getAllItems();

    }

    /***
     * Chunk ordered items to multiple
     * @param $orderItems
     */
    protected function chunkOrderItems($orderItems)
    {
        $totalOrdered = $orderItems->getTotalItemCount();
        $lenOfArray_1 = ciel($totalOrdered/2);
        foreach($orderItems as $orderItem) {

            $item = Mage::getModel('sales/convert_order')->itemToInvoiceItem($orderItem);

        }
    }


}