<?php
/***
 * Class Ordersplitter
 * @desc Create invoice splitters and shipment splitters
 */


class Goldie_Partnersales_Model_Ordersplitter extends Mage_Core_Model_Abstract
{
    protected $order;

    public function __construct(Mage_Sales_Model_Order $order)
    {
        $this->order = $order;
        parent::_construct(); // TODO: Change the autogenerated stub
    }


    public function splitInvoices()
    {
        $this->order->getAllItems();

    }


}